version: '3.4'

services:
  wordpress:
    image: wordpress:5.5.3-php7.2-fpm
    secrets:
      - mysql_user
      - mysql_password
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER_FILE: /run/secrets/mysql_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mysql_password
      WORDPRESS_DB_NAME: cdutten 
    volumes:
      - wordpress:/var/www/html
      - ./config/php-fpm:/etc/php-fpm.d/
    depends_on:
      - db
  nginx:
    image: nginx:1.18.0
    ports:
     - "80:80"
    volumes:
      - wordpress:/var/www/html
      - ./config/nginx:/etc/nginx/conf.d
    healthcheck:
            test: ["CMD", "service", "nginx", "status"]
            interval: 10s
            timeout: 5s
            retries: 5
    depends_on:
      - wordpress
  db:
    image: mysql:5.7
    secrets:
      - mysql_user
      - mysql_password
    environment:
      MYSQL_DATABASE: cdutten
      MYSQL_USER_FILE: /run/secrets/mysql_user 
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
volumes:
  db:
  wordpress:
secrets:
   mysql_user:
       file: ./mysql_user
   mysql_password:
       file: ./mysql_password
