version: '3.4'

services:  
  elasticsearch:
    image: elasticsearch:7.7.1
    environment:
      - node.name=es01
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: kibana:7.7.1
    environment:
       SERVER_NAME: kibana
       ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
  filebeat:
    image: store/elastic/filebeat:7.7.1
    user: root
    volumes:
       - ./config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
       - /var/lib/docker/containers:/var/lib/docker/containers:ro
       - /var/run/docker.sock:/var/run/docker.sock:ro
    command: filebeat -e -strict.perms=false -E setup.kibana.host=kibana:5601

volumes:
    elasticsearch:
